before_install: "chmod +x gradlew"
branches: ~
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle
jdk:
  - openjdk8
language: java
notifications:
  email:
    recipients:
      - bazzi113@naver.com
only:
  - master
script: "./gradlew clean build"